Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -51,7 +51,8 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          set -x
+          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
+          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
           BRANCH=$REPO_BRANCH
           REPO_DATE=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.committer.date')
           BUILD_DATE=$(date --utc +'%y%m%d')
@@ -60,9 +61,14 @@ jobs:
           echo "REPO_DATE=$REPO_DATE" >> $GITHUB_ENV
           echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
           echo "FW_DATE=$FW_DATE" >> $GITHUB_ENV
+          echo "TAG=$TAG" >> $GITHUB_ENV
           wget $REPO_URL/raw/refs/heads/$BRANCH/include/version.mk
-          FW_VER=$(awk -F'[",)]' '/^VERSION_NUMBER:=$(if/ {print $4}' version.mk)
-          [ -z "$FW_VER" ] && { echo "ERROR: Cannot find VERSION_NUMBER"; exit 90; }
+          FW_VER=$(awk -F'[",)]' '/^VERSION_NUMBER:=\$\(if/ {print $4}' version.mk)
+          if [ -z "$FW_VER" ]; then
+            echo "ERROR: Cannot find VERSION_NUMBER in version.mk"
+            exit 90
+          fi
+          echo 'FW_VER = "'$FW_VER'"'
           echo "FW_VER=$FW_VER" >> $GITHUB_ENV
           rm -f version.mk
           {
