Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: build
+name: Optimized Build Workflow
 
 on:
   workflow_dispatch:
@@ -9,8 +9,8 @@ on:
         default: 'false'
         type: choice
         options:
-        - true
-        - false
+          - true
+          - false
       suffix:
         description: 'TAG suffix'
         required: false
@@ -51,22 +51,18 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
-          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
+          set -x
           BRANCH=$REPO_BRANCH
           REPO_DATE=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.committer.date')
-          BUILD_DATE=$( date --utc +'%y%m%d' )
-          FW_DATE=$( date --utc +'%Y-%m-%d' )
+          BUILD_DATE=$(date --utc +'%y%m%d')
+          FW_DATE=$(date --utc +'%Y-%m-%d')
           TAG=$TAG_PREFIX$BUILD_DATE
           echo "REPO_DATE=$REPO_DATE" >> $GITHUB_ENV
           echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
           echo "FW_DATE=$FW_DATE" >> $GITHUB_ENV
-          echo "TAG=$TAG" >> $GITHUB_ENV
           wget $REPO_URL/raw/refs/heads/$BRANCH/include/version.mk
-          FW_VERSION=$( grep -s '^VERSION_NUMBER:=$(if' version.mk 2>/dev/null )
-          [ -z "$FW_VERSION" ] && { echo "ERROR: Cannot find VERSION_NUMBER"; exit 90; }
-          FW_VER=$( echo $FW_VERSION | cut -d"," -f3 | cut -d")" -f1 )
-          echo 'FW_VER = "'$FW_VER'"'
+          FW_VER=$(awk -F'[",)]' '/^VERSION_NUMBER:=$(if/ {print $4}' version.mk)
+          [ -z "$FW_VER" ] && { echo "ERROR: Cannot find VERSION_NUMBER"; exit 90; }
           echo "FW_VER=$FW_VER" >> $GITHUB_ENV
           rm -f version.mk
           {
@@ -90,21 +86,16 @@ jobs:
         run: |
           TIMESTAMP=$(date --utc -d $REPO_DATE +%s)
           DAYS=$(( ( $(date --utc +%s) - $TIMESTAMP ) / 86400 ))
-          echo "Repository activity: $(date --utc -d $REPO_DATE)"
-          echo "Commit: $URL"
-          if [ "${{ github.event_name }}" != "schedule" ]; then
-            is_active=true
-          elif [[ $DAYS -lt 1 ]] ; then
-            is_active=true
+          if [[ "${{ github.event_name }}" != "schedule" || $DAYS -lt 1 ]]; then
+            echo "is_active=true" >> $GITHUB_OUTPUT
           else
             echo "Repository not updated within last 24 hours."
-            is_active=false
+            echo "is_active=false" >> $GITHUB_OUTPUT
           fi
-          echo "is_active=$is_active" >> $GITHUB_OUTPUT
 
   build:
     needs: check
-    #if: needs.check.outputs.is_active == 'true'
+    if: needs.check.outputs.is_active == 'true'
     runs-on: ubuntu-24.04
     strategy:
       fail-fast: false
@@ -124,15 +115,18 @@ jobs:
           - tuf_ax4200
           - tuf_ax6000
     steps:
-      - name: Initialization environment
+      - name: Cache dependencies
+        uses: actions/cache@v3
+        with:
+          path: ${{ github.workspace }}/dependencies-ubuntu.txt
+          key: ${{ runner.os }}-deps-${{ hashFiles('dependencies-ubuntu.txt') }}
+
+      - name: Initialize environment
         env:
           DEBIAN_FRONTEND: noninteractive
         run: |
           sudo apt-get -qq update
-          #sudo apt-get -qq update && sudo apt-get -qq upgrade
           sudo apt-get -qq install $(cat $DEPENDENCIES)
-          sudo apt-get -qq autoremove --purge
-          sudo apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
 
       - name: Maximize build disk space
@@ -143,19 +137,17 @@ jobs:
           remove-haskell: true
           remove-codeql: true
           remove-docker-images: true
-        
+
       - name: Checkout builder
         uses: actions/checkout@main
 
       - name: Download OpenWrt sources
         run: git clone --branch $REPO_BRANCH $REPO_URL.git $BUILD_ROOT
 
-      - name: Init builder
-        env:
-          BLDROOT: ${{ github.workspace }}
-        shell: bash        
+      - name: Initialize builder
+        shell: bash
         run: |
-          rsync -avq --exclude=".*" --exclude="$(basename $BUILD_ROOT)" $BLDROOT/ $BUILD_ROOT/
+          rsync -avq --exclude=".*" --exclude="$(basename $BUILD_ROOT)" ${{ github.workspace }}/ $BUILD_ROOT/
           cd $BUILD_ROOT
           chmod +x *.sh
           wget https://github.com/fantastic-packages/packages/raw/refs/heads/24.10/keys/usign/53FF2B6672243D28.pub
@@ -166,51 +158,37 @@ jobs:
           cd $BUILD_ROOT && ./xupdate.sh -f
           echo "status=success" >> $GITHUB_OUTPUT
 
-      - name: Build the firmware image
+      - name: Build firmware image
         id: compile
         if: steps.update.outputs.status == 'success'
-        env: 
+        env:
           TARGET: ${{ matrix.target }}
           FW_VER: ${{ needs.check.outputs.fw_ver }}
         run: |
+          set -x
           cd $BUILD_ROOT
           MAKE_JOBS=$(($(nproc)+1))
-          echo "$MAKE_JOBS thread compile"
-          # init build config
           ./xmake.sh -I -t $TARGET
-          G_DEVICE_NAME=$( grep -so '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' )
-          [ -z "$G_DEVICE_NAME" ] && exit 31
-          G_BOARD_NAME=$( grep -so '^CONFIG_TARGET_BOARD=.*' .config | cut -d'"' -f2 )
-          [ -z "$G_BOARD_NAME" ] && exit 32
-          G_SUBTARGET_NAME=$( grep -so '^CONFIG_TARGET_SUBTARGET=.*' .config | cut -d'"' -f2 )
-          [ -z "$G_SUBTARGET_NAME" ] && exit 33
+          G_DEVICE_NAME=$(grep -so '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/')
+          G_BOARD_NAME=$(grep -so '^CONFIG_TARGET_BOARD=.*' .config | cut -d'"' -f2)
+          G_SUBTARGET_NAME=$(grep -so '^CONFIG_TARGET_SUBTARGET=.*' .config | cut -d'"' -f2)
           VERMAGIC_LIST="vermagic-$G_BOARD_NAME-$G_SUBTARGET_NAME-*.list"
-          if [ $(find . -maxdepth 1 -name "$VERMAGIC_LIST" | wc -l) = "0" ]; then
-              ./vermagic_update.sh $G_BOARD_NAME $G_SUBTARGET_NAME
+          if [ ! -f $VERMAGIC_LIST ]; then
+            ./vermagic_update.sh $G_BOARD_NAME $G_SUBTARGET_NAME
           fi
-          if [ $(find . -maxdepth 1 -name "$VERMAGIC_LIST" | wc -l) = "0" ]; then
-              exit 41
-          fi
-          # run build
           [ "$FAKE_BUILD" != "true" ] && make -j $MAKE_JOBS download world
-          # process results
           FILE_DATE=$(date --utc +'%y%m%d')
           OUT_DIR=$BUILD_ROOT/bin/targets/$G_BOARD_NAME/$G_SUBTARGET_NAME
           if [ "$FAKE_BUILD" = "true" ]; then
-              mkdir -p logs
-              mkdir -p $OUT_DIR
-              echo "$G_BOARD_NAME $G_SUBTARGET_NAME $G_DEVICE_NAME" > "$OUT_DIR/$G_DEVICE_NAME.txt"
-              touch "$OUT_DIR/kernel-debug.tar.zst"
-              ls -la
-              BLD_VER=$FW_VER
+            mkdir -p logs $OUT_DIR
+            echo "$G_BOARD_NAME $G_SUBTARGET_NAME $G_DEVICE_NAME" > "$OUT_DIR/$G_DEVICE_NAME.txt"
+            touch "$OUT_DIR/kernel-debug.tar.zst"
+            BLD_VER=$FW_VER
           else
-              BLD_VER=$( cat $OUT_DIR/profiles.json | grep -so '"version_number":"[^"]*' | grep -so '[^"]*$' )
+            BLD_VER=$(cat $OUT_DIR/profiles.json | jq -r '.version_number')
           fi
-          echo "Firmware $BLD_VER [$FILE_DATE] builded!"
-          if [ ! -f $OUT_DIR/kernel-debug.tar.zst ]; then
-              echo "File kernel-debug.tar.zst not found!"
-              exit 100
-          fi
+          echo "Firmware $BLD_VER [$FILE_DATE] built!"
+          [ -f $OUT_DIR/kernel-debug.tar.zst ] || { echo "File kernel-debug.tar.zst not found!"; exit 100; }
           echo "status=success" >> $GITHUB_OUTPUT
           echo "DEVICE_NAME=$G_DEVICE_NAME" >> $GITHUB_ENV
           echo "BOARD_NAME=$G_BOARD_NAME" >> $GITHUB_ENV
@@ -219,50 +197,31 @@ jobs:
           echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV
           echo "FILE_DATE=$FILE_DATE" >> $GITHUB_ENV
 
-      - name: Check space usage
-        run: df -hT
-
-      - name: Compress build logs
-        if: always()
-        env:
-          TARGET: ${{ matrix.target }}
-          FW_DATE: ${{ needs.check.outputs.fw_date }}
-          LOGS_DIR: ${{ env.BUILD_ROOT }}/logs
-        run: |
-          tar -cJvf logs-$TARGET-$FW_DATE.tar.xz $LOGS_DIR
-
-      - name: Cleanup OUT directory 
+      - name: Cleanup OUT directory
         if: steps.compile.outputs.status == 'success'
-        env:
-          OUT_DIR: ${{ env.OUT_DIR }}
         run: |
-          cd $OUT_DIR
-          echo "---------------------------"
-          ls -la
-          echo "---------------------------"
-          rm -rf packages
-          rm -f kernel-*
-          rm -f *uImage
-          rm -f *ubi-cleaner*
-          rm -f *-ram-*.bin
+          cd ${{ env.OUT_DIR }}
+          rm -rf packages kernel-* *uImage *ubi-cleaner* *-ram-*.bin
 
-      - name: Upload OUT directory
-        uses: actions/upload-artifact@main
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
         if: steps.compile.outputs.status == 'success'
         with:
           name: openwrt-${{ env.BLD_VER }}-${{ needs.check.outputs.build_date }}-${{ env.DEVICE_NAME }}
           path: ${{ env.OUT_DIR }}
           if-no-files-found: error
 
-      - name: Upload build logs
+      - name: Compress and upload logs
         if: always()
+        run: |
+          tar -cJvf logs-${{ matrix.target }}-${{ env.FW_DATE }}.tar.xz ${{ env.BUILD_ROOT }}/logs
         uses: actions/upload-artifact@v4
         with:
           name: logs-${{ matrix.target }}-${{ env.FW_DATE }}
           path: logs-*.tar.xz
 
   release:
-    needs: [ check, build ]
+    needs: [check, build]
     permissions:
       contents: write
     runs-on: ubuntu-24.04
@@ -274,13 +233,13 @@ jobs:
         with:
           pattern: openwrt-*
 
-      - name: Put images into zip
+      - name: Package images into zip
         run: |
           mkdir -p public
           find . -mindepth 1 -type d -name 'openwrt-*' -exec sh -c 'zip -0 ./public/$(basename {}).zip -j {} {}/*' \;
           ls -lh ./public/*.zip
 
-      - name: Upload assets
+      - name: Create release
         uses: andelf/nightly-release@main
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
